 services:
  - type: web
    name: fastapi-jobboard
    env: python
    plan: free
    autoDeploy: false
    buildCommand: "./build.sh"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"

    buildFilter:
      paths:
        - "frontend"
        - "main.py"
        - "requirements.txt"
        - "build.sh"

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13

